apiVersion: skaffold/v3
kind: Config
metadata:
  name: api-semaphore
build:
  artifacts:
    - image: dockerfile-image
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
portForward:
  - resourceType: service
    resourceName: dockerfile-image
    port: 8100
