apiVersion: skaffold/v3
kind: Config
metadata:
  name: api-semaphore
build:
  artifacts:
    - image: dockerfile-image
      docker:
        dockerfile: Dockerfile
portForward:
  - resourceType: service
    resourceName: dockerfile-image
    port: 8100
manifests:
  rawYaml:
    - service.yaml
profiles:
  - name: target-1
deploy:
  cloudrun: {}
