# action.yml
name: "Build api-semaphore Dockerfile"
description: "Greet someone and record the time"
inputs:
  greetings: # id of input
    description: "Whom to greet"
    required: true
    default: "World"
  mode:
    description: "Which Mode"
    required: true
    default: "test"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "../../Dockerfile"
  args:
    - ${{ inputs.greetings }}
    - ${{ inputs.mode }}
    - ${{ inputs.APP_DB_HOST }}
    - ${{ inputs.APP_DB_PORT }}
    - ${{ inputs.APP_DB_NAME }}
    - ${{ inputs.APP_DB_USERNAME }}
    - ${{ inputs.APP_DB_PASSWORD }}
