# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          PGPASSWORD: postgres

      - name: Test Go Module Container
        uses: ./.github/actions # Uses an action in the .github actions directory
        id: container
        with:
          who-to-greet: "Gary MacDonald"
        env:
          PGPASSWORD: postgres

      # Use the output from the `container` step
      - name: Container Build Output
        run: echo "The time was ${{ steps.container.outputs.time }}"
