# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          # POSTGRES_DB: postgres
          # POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          PGPASSWORD: postgres
          # DATABASE_DSN: "user=postgres host=localhost password=postgres port=5432 database=postgres sslmode=disable"
          # POSTGRES_URL: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"

  hello_gary:
    runs-on: ubuntu-latest
    name: Say Hello Job
    steps:
      # Check out the repository to use action
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello Gary Step
        uses: ./.github/actions # Uses an action in the git hub actions directory
        id: container
        with:
          who-to-greet: "Gary MacDonald"
      # Use the output from the `hello` step
      - name: Gary Step output
        run: echo "The time was ${{ steps.container.outputs.time }}"
