# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    # Permissions, for Google Auth
    permissions:
      contents: "read"
      id-token: "write"

    # Service containers to run with `container-job`
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: postgres
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Local Test
        run: go test -v ./...
        env:
          PGPASSWORD: postgres

      - name: Container Test
        uses: ./.github/actions # Uses an action in the .github actions directory
        id: container
        with:
          who-to-greet: "Gary MacDonald"
        env:
          PGUSER: postgres
          PGPASSWORD: postgres

      - id: Login to GCP
        uses: "google-github-actions/auth@v2"
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure GCloud
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }} #parse the value of repository secret called SERVICE_ACCOUNT_KEY that we have created earlier
          project_id: ${{ env.PROJECT_ID }} #parse the value of env called PROJECT_ID
          export_default_credentials: true

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker # --quiet

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CONTAINER_NAME }}-${{ github.run_number }}
          path: ${{ github.workspace }}

      # - name: Authenticate to Google Cloud
      #   id: auth
      #   uses: google-github-actions/auth@v2
      #   with:
      #     workload_identity_provider: projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/the-workload-pool/providers/the-provider
      #     service_account: ${{ env.SERVICE_NAME }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      # Use the output from the `container` step
      - name: Container Build Output
        run: echo "The time was ${{ steps.container.outputs.time }}"
